name: ci

on:
  push:
    paths:
      - ".github/workflows/ci.yml"
      - src/**

jobs:
  server-docker:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      packages: write
    outputs:
      image: ${{steps.img.outputs.name}}@${{steps.build.outputs.digest}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: img
        name: Generate image name
        run: name="$(echo "ghcr.io/${{github.repository_owner}}/northstar-dedicated-bleeding" | tr "[:upper:]" "[:lower:]")"; echo "${name}"; echo "::set-output name=name::${name}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - id: build
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: src
          push: true
          tags: changeme
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: |
            io.github.generic.northstar-dedicated.northstarmods.version=bleeding